[package]
name = "rust-os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.23"

# used for `cargo build`
[profile.dev]
panic = "abort"

# used for `cargo build --release`
[profile.release]
panic = "abort"
